using UpgradeHelpers.VB6.DB.ADO;
using UpgradeHelpers.VB6.Utils;
using System;
using System.Data.Common;
using System.EnterpriseServices;
using System.Runtime.InteropServices;
using Bull.ApplicationFramework.Legacy;
using Bull.ApplicationFramework;
using Bull.Seguridad.BusinessEntity;
using Bull.Comunes;
using Bull.Comunes.DALCS;
using Bull.Comunes.BusinessLogic;
using Bull.ApplicationFramework.Diagnostics;
using Microsoft.VisualBasic;
using System.Diagnostics;
using System.Globalization;
using System.Data;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Code migration in the day 25/11/2014
//     Centro de Servicios Compartidos.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bull.PRES.Poderes.BusinessLogic
{
    
    
    [Transaction(TransactionOption.NotSupported)]
    [EventTrackingEnabled(true)]
    [Guid("B55F717A-729B-4DAA-8E78-1857536F7D5A"), ClassInterface(ClassInterfaceType.AutoDual)]
    [JustInTimeActivation(true)]
    public class VencPoderes : BusinessLogicAbstract
    {
        
        public   VencPoderes()
        {
        }

        
		[AutoComplete]
		public object DispararBatch(object vcomParamGen, object vcomParamBatch)
		{
            object UACT = null;
            object FECHAOPERA = null;
            object vDebug = null;

			try
			{
				using (new Tracer(new Object[]{vcomParamGen, vcomParamBatch}, UACT, FECHAOPERA, vDebug))
				{


					object result = null;
					modGenericas.Debug4(new object[]{vcomParamGen, vcomParamBatch}, new object[]{"vcomParamGen", "vcomParamBatch"}, "BatchPoder.txt");
					

					ReflectionHelper.SetPrimitiveValue(ref UACT, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) vcomParamBatch).GetValue(1)).GetValue(modGenericas.fCol("UACT", ((Array) vcomParamBatch).GetValue(0)), 0)));
					ReflectionHelper.SetPrimitiveValue(ref FECHAOPERA, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) vcomParamGen).GetValue(1)).GetValue(modGenericas.fCol("FECHA_OPERACION", ((Array) vcomParamGen).GetValue(0)))));
					ReflectionHelper.SetPrimitiveValue(ref vDebug, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) vcomParamBatch).GetValue(1)).GetValue(modGenericas.fCol("DEBUG", ((Array) vcomParamBatch).GetValue(0)), 0)));

					fnarr2ObtDatosPoderes(UACT, FECHAOPERA, "", "", vDebug);


					if (Information.Err().Number != 0)
					{
						throw new System.Exception(Information.Err().Number.ToString() + ", Programa, " + "[" + FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).Comments + ".DispararBatch" + "] " + Information.Err().Description);
					}
					return result;
				}
			}
			catch (System.Exception ex)
			{
				////Codigo agregado por herramienta. 
                Utils.ThrowException(ex, TracePolicy.DbPolicy, System.Reflection.MethodBase.GetCurrentMethod(), UACT, vDebug);
                throw;
			}
			finally
			{
				////Codigo agregado por herramienta
            Utils.LogFinally(TracePolicy.BLPolicy, System.Reflection.MethodBase.GetCurrentMethod(), UACT, vDebug);
           
			}
		}
		[AutoComplete]
		public object fnarr2ObtDatosPoderes(object UACT, object FECHAOPERA, object UANT, object FANT, object vDebug)
		{
			try
			{
				using (new Tracer(new Object[]{UACT, FECHAOPERA, UANT, FANT, vDebug}, UACT, FECHAOPERA, vDebug))
				{


					object result = null;
					object pObjObtPoder = null;
					object ii = null, jj = null;
					object parr2Poderes = null;
					object[] parrDatos = null;
					object indDatos = null;
					object plngPersId1 = null;
					object pComDatos = null;
                    
					object pComUnPoder = null;
					object parr2PoderesApo = null;
					object plngPersId2Apo = null;
					object blnHayDatos = null;
					object parrCampos = null;
					object plngPersId2 = null;
					object[, ] parr2Datos = new object[1, 1];


					ReflectionHelper.SetPrimitiveValue(ref parrCampos, new object[]{"COD_PAIS_EMISOR_CURADOR", "COD_TIPO_DOCUMENTO_CURADOR", "NRO_DOCUMENTO_CURADOR", "PERS_CURADOR", "NOMBRE_CURADOR", "APELLIDO_CURADOR", "COD_PAIS_EMISOR_INCAPAZ", "COD_TIPO_DOCUMENTO_INCAPAZ", "NRO_DOCUMENTO_INCAPAZ", "PERS_INCAPAZ", "NOMBRE_INCAPAZ", "APELLIDO_INCAPAZ", "COD_PODER", "ESTADO", "COD_PAIS_EMISOR_APODERADO", "COD_TIPO_DOCUMENTO_APODERADO", "NRO_DOCUMENTO_APODERADO", "PERS_APODERADO", "NOMBRE_APODERADO", "APELLIDO_APODERADO"});

                    object[,] parr2DatosPoder = new object[((Array)parrCampos).GetUpperBound(0) + 1, 1];

					//1� Obtengo poderes  4,5,6,9 caducados
					pObjObtPoder = Activator.CreateInstance(Type.GetTypeFromProgID("ObtPoder.cObtPoder"));
					ReflectionHelper.SetPrimitiveValue(ref parr2Poderes, ReflectionHelper.Invoke(pObjObtPoder, "fnarr2ObtPoder", new object[]{"", "", "", "", FECHAOPERA, "(4,5,6,9)", "C", "", "", "", "", UACT, null, FECHAOPERA, UANT, FANT, vDebug}));
					VB60Utils.DisposeObject(pObjObtPoder);
					if (!Object.Equals(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(0, 0), null))
					{
						for (double i = 0; i <= ((Array) ((Array) parr2Poderes).GetValue(1)).GetUpperBound(1); i++)
						{
							if (!(Convert.IsDBNull(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("FECHA_FALLECIMIENTO_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))) || Object.Equals(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("FECHA_FALLECIMIENTO_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i)), null)))
							{
								//Esta fallecido

								ReflectionHelper.SetPrimitiveValue(ref plngPersId1, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
								pObjObtPoder = Activator.CreateInstance(Type.GetTypeFromProgID("ObtPoder.cObtPoder"));
								ReflectionHelper.SetPrimitiveValue(ref parr2PoderesApo, ReflectionHelper.Invoke(pObjObtPoder, "fnarr2ObtPoder", new object[]{"", "", plngPersId1, "", "<NULL>", "(1,2,3)", "(O,P)", "", "", "", "", UACT, null, FECHAOPERA, UANT, FANT, vDebug}));
								VB60Utils.DisposeObject(pObjObtPoder);
								if (!Object.Equals(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(0, 0), null))
								{
									ReflectionHelper.SetPrimitiveValue(ref plngPersId2, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
									for (double j = 0; j <= ((Array) ((Array) parr2PoderesApo).GetValue(1)).GetUpperBound(1); j++)
									{
										ReflectionHelper.SetPrimitiveValue(ref plngPersId2Apo, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_2", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
										if (VB60Utils.NotEqual(ReflectionHelper.GetPrimitiveValue(plngPersId2Apo), ReflectionHelper.GetPrimitiveValue(plngPersId2)))
										{
											blnHayDatos = true;

                                            parr2DatosPoder = ArraysHelper.RedimPreserve<object[,]>((object[,])parr2DatosPoder, new int[] { ((Array)parrCampos).GetUpperBound(0) + 1, ReflectionHelper.GetPrimitiveValue<int>(indDatos) + 1 });

											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_PAIS_EMISOR_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PAIS_EMISOR_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_TIPO_DOCUMENTO_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("TIPO_DOCUMENTO_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NRO_DOCUMENTO_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("NRO_DOCUMENTO_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("PERS_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_2", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NOMBRE_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("NOMBRE_2_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("APELLIDO_CURADOR", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("APELLIDO_2_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_PAIS_EMISOR_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PAIS_EMISOR_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_TIPO_DOCUMENTO_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("TIPO_DOCUMENTO_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("PERS_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NRO_DOCUMENTO_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("NRO_DOCUMENTO_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NOMBRE_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("NOMBRE_1_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("APELLIDO_INCAPAZ", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2Poderes).GetValue(1)).GetValue(modGenericas.fCol("APELLIDO_1_1", ((Array) parr2Poderes).GetValue(0)), Convert.ToInt32(i))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_PODER", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("COD_PODER", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("ESTADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("ESTADO", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_PAIS_EMISOR_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("PAIS_EMISOR_2", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("COD_TIPO_DOCUMENTO_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("TIPO_DOCUMENTO_2", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NRO_DOCUMENTO_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("NRO_DOCUMENTO_2", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("PERS_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("PERS_IDENTIFICADOR_2", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("NOMBRE_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("NOMBRE_2_1", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));
											ReflectionHelper.SetPrimitiveValue(ref parr2DatosPoder[modGenericas.fCol("APELLIDO_APODERADO", parrCampos), ReflectionHelper.GetPrimitiveValue<int>(indDatos)], ReflectionHelper.GetPrimitiveValue(((Array) ((Array) parr2PoderesApo).GetValue(1)).GetValue(modGenericas.fCol("APELLIDO_2_1", ((Array) parr2PoderesApo).GetValue(0)), Convert.ToInt32(j))));

											indDatos = ReflectionHelper.GetPrimitiveValue<double>(indDatos) + 1;
										}
									}
								}
							}
						}
					}
					if (ReflectionHelper.GetPrimitiveValue<bool>(blnHayDatos))
					{
						result = new object[]{parrCampos, parr2DatosPoder};
					}
					else
					{
						result = new object[]{parrCampos, parr2Datos};
					}
					object pObjAdmParamGrales = null;
					object pRetParamGrales = null;
					object pstrMailOperaciones = null;

					pObjAdmParamGrales = Activator.CreateInstance(Type.GetTypeFromProgID("AdmParamGrales.cAdmParamGrales"));
					ReflectionHelper.SetPrimitiveValue(ref pRetParamGrales, ReflectionHelper.Invoke(pObjAdmParamGrales, "fnarr2ObtParamGrales", new object[]{"", "", "", "", "", "", "", "", "DESTINATARIO DE REPORTES BATCH A OPERACIONES BULL", "DDRBAOB", "S", "", UACT, FECHAOPERA, "", "", vDebug}));
					VB60Utils.DisposeObject(pObjAdmParamGrales);
					if (!Object.Equals(((Array) ((Array) pRetParamGrales).GetValue(1)).GetValue(0, 0), null))
					{
						ReflectionHelper.SetPrimitiveValue(ref pstrMailOperaciones, ReflectionHelper.GetPrimitiveValue(((Array) ((Array) pRetParamGrales).GetValue(1)).GetValue(0, 0)));
					}

					object pobjMTP3 = null;
					object pComParamRep = null;

					object parrCabezal = null;

					ReflectionHelper.SetPrimitiveValue(ref parrCabezal, new object[]{"COM_DATOS", "UACT", "FACT", "VDEBUG", "FECHAOPERA", "MAIL", "DIR_TMPL_XLS", "DIR_REPORTE"});

                    object[,] parr2DatosReporte = new object[((Array)parrCabezal).GetUpperBound(0) + 1, 1];
                    parr2DatosReporte = ArraysHelper.RedimPreserve<object[,]>((object[,])parr2DatosReporte, new int[] { ((Array)parrCabezal).GetUpperBound(0) + 1,1});

					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("COM_DATOS", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(result));
					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("UACT", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(UACT));
					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("FACT", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(FECHAOPERA));
					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("VDEBUG", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(vDebug));
					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("FECHAOPERA", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(FECHAOPERA));
					ReflectionHelper.SetPrimitiveValue(ref parr2DatosReporte[modGenericas.fCol("MAIL", parrCabezal), 0], ReflectionHelper.GetPrimitiveValue(pstrMailOperaciones));
					parr2DatosReporte[modGenericas.fCol("DIR_TMPL_XLS", parrCabezal), 0] = "\\RepXLSTmpl$\\" + "RepPoderes.xlt";

					parr2DatosReporte[modGenericas.fCol("DIR_REPORTE", parrCabezal), 0] = "\\AppLog$\\ReportesXLS\\";

					ReflectionHelper.SetPrimitiveValue(ref pComParamRep, new object[]{parrCabezal, parr2DatosReporte});

					pobjMTP3 = Activator.CreateInstance(Type.GetTypeFromProgID("DispReporte.cDispReporte"));
					ReflectionHelper.Invoke(pobjMTP3, "DispRep", new object[]{"GenReportePoderes.cGenReportePoderes", pComParamRep});
					VB60Utils.DisposeObject(pobjMTP3);


					if (Information.Err().Number != 0)
					{
						throw new System.Exception(Information.Err().Number.ToString() + ", Programa, " + "[" + FileVersionInfo.GetVersionInfo(System.Reflection.Assembly.GetExecutingAssembly().Location).Comments + ".fnarr2ObtDatosPoderes" + "] " + Information.Err().Description);
					}
					return result;
				}
			}
			catch (System.Exception ex)
			{
				////Codigo agregado por herramienta. 
                Utils.ThrowException(ex, TracePolicy.DbPolicy, System.Reflection.MethodBase.GetCurrentMethod(), UACT, vDebug);
                throw;
			}
			finally
			{
				////Codigo agregado por herramienta
            Utils.LogFinally(TracePolicy.BLPolicy, System.Reflection.MethodBase.GetCurrentMethod(), UACT, vDebug);
           
			}
		}
	}
}













































