//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bull.PRES.Poderes.ServiceAgents.wsPersonas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamObtPersonaPorDocumento", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    public partial class ParamObtPersonaPorDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodPaisEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodPaisEmisor {
            get {
                return this.CodPaisEmisorField;
            }
            set {
                if ((this.CodPaisEmisorField.Equals(value) != true)) {
                    this.CodPaisEmisorField = value;
                    this.RaisePropertyChanged("CodPaisEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtPersona", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorPersId))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorDocumento))]
    public partial class ResultObtPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Bull.PRES.Poderes.ServiceAgents.wsPersonas.ObjPersona ObjPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ObjPersona ObjPersona {
            get {
                return this.ObjPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjPersonaField, value) != true)) {
                    this.ObjPersonaField = value;
                    this.RaisePropertyChanged("ObjPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjPersona", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    public partial class ObjPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodPaisEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        private int PersIdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido2Field;
        
        private int SexoField;
        
        private System.DateTime FechaNacimientoField;
        
        private int CodNacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieCCField;
        
        private int NroCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoGeneradoField;
        
        private int CodOpcionRegimenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescOpcionRegimenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        private System.DateTime FechaFallecimientoField;
        
        private int CodCausalFallecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescCodCausalFallecimientoField;
        
        private System.DateTime FechaComunicacionField;
        
        private int ActaField;
        
        private int OficinaJuridicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptoOficinaJuridicaField;
        
        private int CodAgenciaField;
        
        private System.DateTime FactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescCodPaisEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescCodNacionalidadField;
        
        private int CodPaisFallecimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescCodPaisFallecimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodPaisEmisor {
            get {
                return this.CodPaisEmisorField;
            }
            set {
                if ((this.CodPaisEmisorField.Equals(value) != true)) {
                    this.CodPaisEmisorField = value;
                    this.RaisePropertyChanged("CodPaisEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodTipoDocumento {
            get {
                return this.CodTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoDocumentoField, value) != true)) {
                    this.CodTipoDocumentoField = value;
                    this.RaisePropertyChanged("CodTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersIdentificador {
            get {
                return this.PersIdentificadorField;
            }
            set {
                if ((this.PersIdentificadorField.Equals(value) != true)) {
                    this.PersIdentificadorField = value;
                    this.RaisePropertyChanged("PersIdentificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Nombre1 {
            get {
                return this.Nombre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre1Field, value) != true)) {
                    this.Nombre1Field = value;
                    this.RaisePropertyChanged("Nombre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nombre2 {
            get {
                return this.Nombre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre2Field, value) != true)) {
                    this.Nombre2Field = value;
                    this.RaisePropertyChanged("Nombre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int CodNacionalidad {
            get {
                return this.CodNacionalidadField;
            }
            set {
                if ((this.CodNacionalidadField.Equals(value) != true)) {
                    this.CodNacionalidadField = value;
                    this.RaisePropertyChanged("CodNacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SerieCC {
            get {
                return this.SerieCCField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieCCField, value) != true)) {
                    this.SerieCCField = value;
                    this.RaisePropertyChanged("SerieCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int NroCC {
            get {
                return this.NroCCField;
            }
            set {
                if ((this.NroCCField.Equals(value) != true)) {
                    this.NroCCField = value;
                    this.RaisePropertyChanged("NroCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string AutoGenerado {
            get {
                return this.AutoGeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoGeneradoField, value) != true)) {
                    this.AutoGeneradoField = value;
                    this.RaisePropertyChanged("AutoGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int CodOpcionRegimen {
            get {
                return this.CodOpcionRegimenField;
            }
            set {
                if ((this.CodOpcionRegimenField.Equals(value) != true)) {
                    this.CodOpcionRegimenField = value;
                    this.RaisePropertyChanged("CodOpcionRegimen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DescOpcionRegimen {
            get {
                return this.DescOpcionRegimenField;
            }
            set {
                if ((object.ReferenceEquals(this.DescOpcionRegimenField, value) != true)) {
                    this.DescOpcionRegimenField = value;
                    this.RaisePropertyChanged("DescOpcionRegimen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime FechaFallecimiento {
            get {
                return this.FechaFallecimientoField;
            }
            set {
                if ((this.FechaFallecimientoField.Equals(value) != true)) {
                    this.FechaFallecimientoField = value;
                    this.RaisePropertyChanged("FechaFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int CodCausalFallecimiento {
            get {
                return this.CodCausalFallecimientoField;
            }
            set {
                if ((this.CodCausalFallecimientoField.Equals(value) != true)) {
                    this.CodCausalFallecimientoField = value;
                    this.RaisePropertyChanged("CodCausalFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string DescCodCausalFallecimiento {
            get {
                return this.DescCodCausalFallecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescCodCausalFallecimientoField, value) != true)) {
                    this.DescCodCausalFallecimientoField = value;
                    this.RaisePropertyChanged("DescCodCausalFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.DateTime FechaComunicacion {
            get {
                return this.FechaComunicacionField;
            }
            set {
                if ((this.FechaComunicacionField.Equals(value) != true)) {
                    this.FechaComunicacionField = value;
                    this.RaisePropertyChanged("FechaComunicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int Acta {
            get {
                return this.ActaField;
            }
            set {
                if ((this.ActaField.Equals(value) != true)) {
                    this.ActaField = value;
                    this.RaisePropertyChanged("Acta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int OficinaJuridica {
            get {
                return this.OficinaJuridicaField;
            }
            set {
                if ((this.OficinaJuridicaField.Equals(value) != true)) {
                    this.OficinaJuridicaField = value;
                    this.RaisePropertyChanged("OficinaJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string DeptoOficinaJuridica {
            get {
                return this.DeptoOficinaJuridicaField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptoOficinaJuridicaField, value) != true)) {
                    this.DeptoOficinaJuridicaField = value;
                    this.RaisePropertyChanged("DeptoOficinaJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int CodAgencia {
            get {
                return this.CodAgenciaField;
            }
            set {
                if ((this.CodAgenciaField.Equals(value) != true)) {
                    this.CodAgenciaField = value;
                    this.RaisePropertyChanged("CodAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public System.DateTime Fact {
            get {
                return this.FactField;
            }
            set {
                if ((this.FactField.Equals(value) != true)) {
                    this.FactField = value;
                    this.RaisePropertyChanged("Fact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string DescCodPaisEmisor {
            get {
                return this.DescCodPaisEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescCodPaisEmisorField, value) != true)) {
                    this.DescCodPaisEmisorField = value;
                    this.RaisePropertyChanged("DescCodPaisEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string DescSexo {
            get {
                return this.DescSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescSexoField, value) != true)) {
                    this.DescSexoField = value;
                    this.RaisePropertyChanged("DescSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string DescCodNacionalidad {
            get {
                return this.DescCodNacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DescCodNacionalidadField, value) != true)) {
                    this.DescCodNacionalidadField = value;
                    this.RaisePropertyChanged("DescCodNacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public int CodPaisFallecimiento {
            get {
                return this.CodPaisFallecimientoField;
            }
            set {
                if ((this.CodPaisFallecimientoField.Equals(value) != true)) {
                    this.CodPaisFallecimientoField = value;
                    this.RaisePropertyChanged("CodPaisFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string DescCodPaisFallecimiento {
            get {
                return this.DescCodPaisFallecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescCodPaisFallecimientoField, value) != true)) {
                    this.DescCodPaisFallecimientoField = value;
                    this.RaisePropertyChanged("DescCodPaisFallecimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtPersonaPorPersId", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    public partial class ResultObtPersonaPorPersId : Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersona {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtPersonaPorDocumento", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    public partial class ResultObtPersonaPorDocumento : Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersona {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamObtPersonaPorPersId", Namespace="http://bps.gub.uy/Personas/wsPersonas/v001")]
    [System.SerializableAttribute()]
    public partial class ParamObtPersonaPorPersId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersId {
            get {
                return this.PersIdField;
            }
            set {
                if ((this.PersIdField.Equals(value) != true)) {
                    this.PersIdField = value;
                    this.RaisePropertyChanged("PersId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bps.gub.uy/Personas/wsPersonas", ConfigurationName="wsPersonas.wsPersonas")]
    public interface wsPersonas {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://bps.gub.uy/Personas/wsPersonas/v001) of message obtPersonaPorDocumentoRequest does not match the default value (http://bps.gub.uy/Personas/wsPersonas)
        [System.ServiceModel.OperationContractAttribute(Action="obtPersonaPorDocumento", ReplyAction="*")]
        Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoResponse obtPersonaPorDocumento(Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://bps.gub.uy/Personas/wsPersonas/v001) of message obtPersonaPorPersIdRequest does not match the default value (http://bps.gub.uy/Personas/wsPersonas)
        [System.ServiceModel.OperationContractAttribute(Action="obtPersonaPorPersId", ReplyAction="*")]
        Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdResponse obtPersonaPorPersId(Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtPersonaPorDocumento", WrapperNamespace="http://bps.gub.uy/Personas/wsPersonas/v001", IsWrapped=true)]
    public partial class obtPersonaPorDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personas/wsPersonas/v001", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorDocumento paramObtPersonaPorDocumento;
        
        public obtPersonaPorDocumentoRequest() {
        }
        
        public obtPersonaPorDocumentoRequest(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorDocumento paramObtPersonaPorDocumento) {
            this.paramObtPersonaPorDocumento = paramObtPersonaPorDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtPersonaPorDocumentoResponse", WrapperNamespace="http://bps.gub.uy/Personas/wsPersonas/v001", IsWrapped=true)]
    public partial class obtPersonaPorDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personas/wsPersonas/v001", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorDocumento obtPersonaPorDocumentoResult;
        
        public obtPersonaPorDocumentoResponse() {
        }
        
        public obtPersonaPorDocumentoResponse(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorDocumento obtPersonaPorDocumentoResult) {
            this.obtPersonaPorDocumentoResult = obtPersonaPorDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtPersonaPorPersId", WrapperNamespace="http://bps.gub.uy/Personas/wsPersonas/v001", IsWrapped=true)]
    public partial class obtPersonaPorPersIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personas/wsPersonas/v001", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorPersId paramObtPersonaPorPersId;
        
        public obtPersonaPorPersIdRequest() {
        }
        
        public obtPersonaPorPersIdRequest(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorPersId paramObtPersonaPorPersId) {
            this.paramObtPersonaPorPersId = paramObtPersonaPorPersId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtPersonaPorPersIdResponse", WrapperNamespace="http://bps.gub.uy/Personas/wsPersonas/v001", IsWrapped=true)]
    public partial class obtPersonaPorPersIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personas/wsPersonas/v001", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorPersId obtPersonaPorPersIdResult;
        
        public obtPersonaPorPersIdResponse() {
        }
        
        public obtPersonaPorPersIdResponse(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorPersId obtPersonaPorPersIdResult) {
            this.obtPersonaPorPersIdResult = obtPersonaPorPersIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPersonasChannel : Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPersonasClient : System.ServiceModel.ClientBase<Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas>, Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas {
        
        public wsPersonasClient() {
        }
        
        public wsPersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoResponse Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas.obtPersonaPorDocumento(Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoRequest request) {
            return base.Channel.obtPersonaPorDocumento(request);
        }
        
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorDocumento obtPersonaPorDocumento(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorDocumento paramObtPersonaPorDocumento) {
            Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoRequest inValue = new Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoRequest();
            inValue.paramObtPersonaPorDocumento = paramObtPersonaPorDocumento;
            Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorDocumentoResponse retVal = ((Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas)(this)).obtPersonaPorDocumento(inValue);
            return retVal.obtPersonaPorDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdResponse Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas.obtPersonaPorPersId(Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdRequest request) {
            return base.Channel.obtPersonaPorPersId(request);
        }
        
        public Bull.PRES.Poderes.ServiceAgents.wsPersonas.ResultObtPersonaPorPersId obtPersonaPorPersId(Bull.PRES.Poderes.ServiceAgents.wsPersonas.ParamObtPersonaPorPersId paramObtPersonaPorPersId) {
            Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdRequest inValue = new Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdRequest();
            inValue.paramObtPersonaPorPersId = paramObtPersonaPorPersId;
            Bull.PRES.Poderes.ServiceAgents.wsPersonas.obtPersonaPorPersIdResponse retVal = ((Bull.PRES.Poderes.ServiceAgents.wsPersonas.wsPersonas)(this)).obtPersonaPorPersId(inValue);
            return retVal.obtPersonaPorPersIdResult;
        }
    }
}
