//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bull.PRES.Poderes.ServiceWF.SReferencePersonas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextoServicio", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class ContextoServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AgenciaField;
        
        private System.Nullable<int> CodRolField;
        
        private int DebugField;
        
        private System.DateTime FechaOperaField;
        
        private int FuncionField;
        
        private int ModuloField;
        
        private int PaqueteField;
        
        private int SistemaField;
        
        private int SubSistemaField;
        
        private string UactField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Agencia {
            get {
                return this.AgenciaField;
            }
            set {
                if ((this.AgenciaField.Equals(value) != true)) {
                    this.AgenciaField = value;
                    this.RaisePropertyChanged("Agencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodRol {
            get {
                return this.CodRolField;
            }
            set {
                if ((this.CodRolField.Equals(value) != true)) {
                    this.CodRolField = value;
                    this.RaisePropertyChanged("CodRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Debug {
            get {
                return this.DebugField;
            }
            set {
                if ((this.DebugField.Equals(value) != true)) {
                    this.DebugField = value;
                    this.RaisePropertyChanged("Debug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaOpera {
            get {
                return this.FechaOperaField;
            }
            set {
                if ((this.FechaOperaField.Equals(value) != true)) {
                    this.FechaOperaField = value;
                    this.RaisePropertyChanged("FechaOpera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Funcion {
            get {
                return this.FuncionField;
            }
            set {
                if ((this.FuncionField.Equals(value) != true)) {
                    this.FuncionField = value;
                    this.RaisePropertyChanged("Funcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Modulo {
            get {
                return this.ModuloField;
            }
            set {
                if ((this.ModuloField.Equals(value) != true)) {
                    this.ModuloField = value;
                    this.RaisePropertyChanged("Modulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Paquete {
            get {
                return this.PaqueteField;
            }
            set {
                if ((this.PaqueteField.Equals(value) != true)) {
                    this.PaqueteField = value;
                    this.RaisePropertyChanged("Paquete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((this.SistemaField.Equals(value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SubSistema {
            get {
                return this.SubSistemaField;
            }
            set {
                if ((this.SubSistemaField.Equals(value) != true)) {
                    this.SubSistemaField = value;
                    this.RaisePropertyChanged("SubSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Uact {
            get {
                return this.UactField;
            }
            set {
                if ((object.ReferenceEquals(this.UactField, value) != true)) {
                    this.UactField = value;
                    this.RaisePropertyChanged("Uact");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtPersonaPorDocumento", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class ResultObtPersonaPorDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ErrorNegocio[] ColErrorNegocioField;
        
        private Bull.PRES.Poderes.ServiceWF.SReferencePersonas.PersonaCons PersonaConsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ErrorNegocio[] ColErrorNegocio {
            get {
                return this.ColErrorNegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.ColErrorNegocioField, value) != true)) {
                    this.ColErrorNegocioField = value;
                    this.RaisePropertyChanged("ColErrorNegocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.PersonaCons PersonaCons {
            get {
                return this.PersonaConsField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaConsField, value) != true)) {
                    this.PersonaConsField = value;
                    this.RaisePropertyChanged("PersonaCons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaCons", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class PersonaCons : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Apellido1Field;
        
        private string Apellido2Field;
        
        private string AutogeneradoField;
        
        private System.Nullable<int> CodNacionalidadField;
        
        private System.Nullable<int> CodSexoField;
        
        private Bull.PRES.Poderes.ServiceWF.SReferencePersonas.DocumentoCons DocumentoConsField;
        
        private Bull.PRES.Poderes.ServiceWF.SReferencePersonas.FallecimientoCons FallecimientoConsField;
        
        private System.Nullable<System.DateTime> FechaAltaField;
        
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        private string NacionalidadDescField;
        
        private string Nombre1Field;
        
        private string Nombre2Field;
        
        private System.Nullable<int> NumeroCCField;
        
        private string ObservacionesField;
        
        private Bull.PRES.Poderes.ServiceWF.SReferencePersonas.OpcionRegimenCons OpRegimenConsField;
        
        private string SerieCCField;
        
        private string SexoDescField;
        
        private string SistemaDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Apellido1 {
            get {
                return this.Apellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido1Field, value) != true)) {
                    this.Apellido1Field = value;
                    this.RaisePropertyChanged("Apellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Apellido2 {
            get {
                return this.Apellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido2Field, value) != true)) {
                    this.Apellido2Field = value;
                    this.RaisePropertyChanged("Apellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Autogenerado {
            get {
                return this.AutogeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutogeneradoField, value) != true)) {
                    this.AutogeneradoField = value;
                    this.RaisePropertyChanged("Autogenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodNacionalidad {
            get {
                return this.CodNacionalidadField;
            }
            set {
                if ((this.CodNacionalidadField.Equals(value) != true)) {
                    this.CodNacionalidadField = value;
                    this.RaisePropertyChanged("CodNacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodSexo {
            get {
                return this.CodSexoField;
            }
            set {
                if ((this.CodSexoField.Equals(value) != true)) {
                    this.CodSexoField = value;
                    this.RaisePropertyChanged("CodSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.DocumentoCons DocumentoCons {
            get {
                return this.DocumentoConsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoConsField, value) != true)) {
                    this.DocumentoConsField = value;
                    this.RaisePropertyChanged("DocumentoCons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.FallecimientoCons FallecimientoCons {
            get {
                return this.FallecimientoConsField;
            }
            set {
                if ((object.ReferenceEquals(this.FallecimientoConsField, value) != true)) {
                    this.FallecimientoConsField = value;
                    this.RaisePropertyChanged("FallecimientoCons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NacionalidadDesc {
            get {
                return this.NacionalidadDescField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadDescField, value) != true)) {
                    this.NacionalidadDescField = value;
                    this.RaisePropertyChanged("NacionalidadDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre1 {
            get {
                return this.Nombre1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre1Field, value) != true)) {
                    this.Nombre1Field = value;
                    this.RaisePropertyChanged("Nombre1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre2 {
            get {
                return this.Nombre2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre2Field, value) != true)) {
                    this.Nombre2Field = value;
                    this.RaisePropertyChanged("Nombre2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> NumeroCC {
            get {
                return this.NumeroCCField;
            }
            set {
                if ((this.NumeroCCField.Equals(value) != true)) {
                    this.NumeroCCField = value;
                    this.RaisePropertyChanged("NumeroCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.OpcionRegimenCons OpRegimenCons {
            get {
                return this.OpRegimenConsField;
            }
            set {
                if ((object.ReferenceEquals(this.OpRegimenConsField, value) != true)) {
                    this.OpRegimenConsField = value;
                    this.RaisePropertyChanged("OpRegimenCons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SerieCC {
            get {
                return this.SerieCCField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieCCField, value) != true)) {
                    this.SerieCCField = value;
                    this.RaisePropertyChanged("SerieCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SexoDesc {
            get {
                return this.SexoDescField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoDescField, value) != true)) {
                    this.SexoDescField = value;
                    this.RaisePropertyChanged("SexoDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SistemaDesc {
            get {
                return this.SistemaDescField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaDescField, value) != true)) {
                    this.SistemaDescField = value;
                    this.RaisePropertyChanged("SistemaDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorNegocio", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class ErrorNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private int SeveridadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Severidad {
            get {
                return this.SeveridadField;
            }
            set {
                if ((this.SeveridadField.Equals(value) != true)) {
                    this.SeveridadField = value;
                    this.RaisePropertyChanged("Severidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoCons", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class DocumentoCons : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CodPaisEmisorField;
        
        private string CodTipoDocDescField;
        
        private string CodTipoDocumentoField;
        
        private string NroDocumentoField;
        
        private string PaisEmisorDescField;
        
        private System.Nullable<int> PersIdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodPaisEmisor {
            get {
                return this.CodPaisEmisorField;
            }
            set {
                if ((this.CodPaisEmisorField.Equals(value) != true)) {
                    this.CodPaisEmisorField = value;
                    this.RaisePropertyChanged("CodPaisEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodTipoDocDesc {
            get {
                return this.CodTipoDocDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoDocDescField, value) != true)) {
                    this.CodTipoDocDescField = value;
                    this.RaisePropertyChanged("CodTipoDocDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodTipoDocumento {
            get {
                return this.CodTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoDocumentoField, value) != true)) {
                    this.CodTipoDocumentoField = value;
                    this.RaisePropertyChanged("CodTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaisEmisorDesc {
            get {
                return this.PaisEmisorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisEmisorDescField, value) != true)) {
                    this.PaisEmisorDescField = value;
                    this.RaisePropertyChanged("PaisEmisorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> PersIdentificador {
            get {
                return this.PersIdentificadorField;
            }
            set {
                if ((this.PersIdentificadorField.Equals(value) != true)) {
                    this.PersIdentificadorField = value;
                    this.RaisePropertyChanged("PersIdentificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallecimientoCons", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class FallecimientoCons : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> ActaField;
        
        private string CausalFallecimientoDescField;
        
        private System.Nullable<int> CodCausalFallecimientoField;
        
        private System.Nullable<int> CodPaisFallecimientoField;
        
        private string DepOfJuridicaField;
        
        private System.DateTime FechaComunicacionField;
        
        private System.DateTime FechaFallecimientoField;
        
        private System.Nullable<int> OfJuridicaField;
        
        private string PaisFallecDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Acta {
            get {
                return this.ActaField;
            }
            set {
                if ((this.ActaField.Equals(value) != true)) {
                    this.ActaField = value;
                    this.RaisePropertyChanged("Acta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CausalFallecimientoDesc {
            get {
                return this.CausalFallecimientoDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CausalFallecimientoDescField, value) != true)) {
                    this.CausalFallecimientoDescField = value;
                    this.RaisePropertyChanged("CausalFallecimientoDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodCausalFallecimiento {
            get {
                return this.CodCausalFallecimientoField;
            }
            set {
                if ((this.CodCausalFallecimientoField.Equals(value) != true)) {
                    this.CodCausalFallecimientoField = value;
                    this.RaisePropertyChanged("CodCausalFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodPaisFallecimiento {
            get {
                return this.CodPaisFallecimientoField;
            }
            set {
                if ((this.CodPaisFallecimientoField.Equals(value) != true)) {
                    this.CodPaisFallecimientoField = value;
                    this.RaisePropertyChanged("CodPaisFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepOfJuridica {
            get {
                return this.DepOfJuridicaField;
            }
            set {
                if ((object.ReferenceEquals(this.DepOfJuridicaField, value) != true)) {
                    this.DepOfJuridicaField = value;
                    this.RaisePropertyChanged("DepOfJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaComunicacion {
            get {
                return this.FechaComunicacionField;
            }
            set {
                if ((this.FechaComunicacionField.Equals(value) != true)) {
                    this.FechaComunicacionField = value;
                    this.RaisePropertyChanged("FechaComunicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaFallecimiento {
            get {
                return this.FechaFallecimientoField;
            }
            set {
                if ((this.FechaFallecimientoField.Equals(value) != true)) {
                    this.FechaFallecimientoField = value;
                    this.RaisePropertyChanged("FechaFallecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> OfJuridica {
            get {
                return this.OfJuridicaField;
            }
            set {
                if ((this.OfJuridicaField.Equals(value) != true)) {
                    this.OfJuridicaField = value;
                    this.RaisePropertyChanged("OfJuridica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaisFallecDesc {
            get {
                return this.PaisFallecDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisFallecDescField, value) != true)) {
                    this.PaisFallecDescField = value;
                    this.RaisePropertyChanged("PaisFallecDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpcionRegimenCons", Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona")]
    [System.SerializableAttribute()]
    public partial class OpcionRegimenCons : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> CodOpcionRegimenField;
        
        private string CodOpcionRegimenDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> CodOpcionRegimen {
            get {
                return this.CodOpcionRegimenField;
            }
            set {
                if ((this.CodOpcionRegimenField.Equals(value) != true)) {
                    this.CodOpcionRegimenField = value;
                    this.RaisePropertyChanged("CodOpcionRegimen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodOpcionRegimenDesc {
            get {
                return this.CodOpcionRegimenDescField;
            }
            set {
                if ((object.ReferenceEquals(this.CodOpcionRegimenDescField, value) != true)) {
                    this.CodOpcionRegimenDescField = value;
                    this.RaisePropertyChanged("CodOpcionRegimenDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bps.gub.uy/RegistrosCorporativos/Persona", ConfigurationName="SReferencePersonas.svc_Rcor_Personas")]
    public interface svc_Rcor_Personas {
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtPersonaPorDocumento", ReplyAction="*")]
        Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ResultObtPersonaPorDocumento ObtPersonaPorDocumento(int codPaisEmisor, string codTipoDocumento, string nroDocumento, Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ContextoServicio contexto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface svc_Rcor_PersonasChannel : Bull.PRES.Poderes.ServiceWF.SReferencePersonas.svc_Rcor_Personas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class svc_Rcor_PersonasClient : System.ServiceModel.ClientBase<Bull.PRES.Poderes.ServiceWF.SReferencePersonas.svc_Rcor_Personas>, Bull.PRES.Poderes.ServiceWF.SReferencePersonas.svc_Rcor_Personas {
        
        public svc_Rcor_PersonasClient() {
        }
        
        public svc_Rcor_PersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svc_Rcor_PersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svc_Rcor_PersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svc_Rcor_PersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ResultObtPersonaPorDocumento ObtPersonaPorDocumento(int codPaisEmisor, string codTipoDocumento, string nroDocumento, Bull.PRES.Poderes.ServiceWF.SReferencePersonas.ContextoServicio contexto) {
            return base.Channel.ObtPersonaPorDocumento(codPaisEmisor, codTipoDocumento, nroDocumento, contexto);
        }
    }
}
