//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bull.PRES.Poderes.ServiceWF.SReferencePoderes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamObtTienePoder", Namespace="http://bps.gub.uy/Prestaciones/wsPoderes/v001")]
    [System.SerializableAttribute()]
    public partial class ParamObtTienePoder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersIdentificadorPoderDanteField;
        
        private System.Nullable<int> PersIdentificadorApoderadoField;
        
        private int CodGrupoField;
        
        private Bull.ApplicationFramework.WebServices.ContextoWS CtxWSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersIdentificadorPoderDante {
            get {
                return this.PersIdentificadorPoderDanteField;
            }
            set {
                if ((this.PersIdentificadorPoderDanteField.Equals(value) != true)) {
                    this.PersIdentificadorPoderDanteField = value;
                    this.RaisePropertyChanged("PersIdentificadorPoderDante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> PersIdentificadorApoderado {
            get {
                return this.PersIdentificadorApoderadoField;
            }
            set {
                if ((this.PersIdentificadorApoderadoField.Equals(value) != true)) {
                    this.PersIdentificadorApoderadoField = value;
                    this.RaisePropertyChanged("PersIdentificadorApoderado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int CodGrupo {
            get {
                return this.CodGrupoField;
            }
            set {
                if ((this.CodGrupoField.Equals(value) != true)) {
                    this.CodGrupoField = value;
                    this.RaisePropertyChanged("CodGrupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Bull.ApplicationFramework.WebServices.ContextoWS CtxWS {
            get {
                return this.CtxWSField;
            }
            set {
                if ((object.ReferenceEquals(this.CtxWSField, value) != true)) {
                    this.CtxWSField = value;
                    this.RaisePropertyChanged("CtxWS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObtTienePoder", Namespace="http://bps.gub.uy/Prestaciones/wsPoderes/v001")]
    [System.SerializableAttribute()]
    public partial class ResultObtTienePoder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bps.gub.uy/Prestaciones/Poderes/", ConfigurationName="SReferencePoderes.ServicioPoderes")]
    public interface ServicioPoderes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bps.gub.uy/Prestaciones/Poderes/ServicioPoderes/ObtTienePoder", ReplyAction="http://bps.gub.uy/Prestaciones/Poderes/ServicioPoderes/ObtTienePoderResponse")]
        Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ResultObtTienePoder ObtTienePoder(Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ParamObtTienePoder paramObtTienePoder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServicioPoderesChannel : Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ServicioPoderes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServicioPoderesClient : System.ServiceModel.ClientBase<Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ServicioPoderes>, Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ServicioPoderes {
        
        public ServicioPoderesClient() {
        }
        
        public ServicioPoderesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPoderesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPoderesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPoderesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ResultObtTienePoder ObtTienePoder(Bull.PRES.Poderes.ServiceWF.SReferencePoderes.ParamObtTienePoder paramObtTienePoder) {
            return base.Channel.ObtTienePoder(paramObtTienePoder);
        }
    }
}
