//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", ConfigurationName="wssFuncionarios.IVirtualInterface")]
    public interface IVirtualInterface {
        
        // CODEGEN: Generating message contract since the operation version is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="version", ReplyAction="versionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionResponse version(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionRequest request);
        
        // CODEGEN: Generating message contract since the operation obtenerEgresadosPeriodo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="obtenerEgresadosPeriodo", ReplyAction="obtenerEgresadosPeriodoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoResponse obtenerEgresadosPeriodo(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoRequest request);
        
        // CODEGEN: Generating message contract since the operation obtenerFuncionarios is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="obtenerFuncionarios", ReplyAction="obtenerFuncionariosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosResponse obtenerFuncionarios(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class version : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ItemFuncionario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificadorFuncionario identificadorFuncionarioField;
        
        private Funcionario funcionarioField;
        
        private ErrorNegocio[] erroresNegocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public IdentificadorFuncionario identificadorFuncionario {
            get {
                return this.identificadorFuncionarioField;
            }
            set {
                this.identificadorFuncionarioField = value;
                this.RaisePropertyChanged("identificadorFuncionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Funcionario funcionario {
            get {
                return this.funcionarioField;
            }
            set {
                this.funcionarioField = value;
                this.RaisePropertyChanged("funcionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errorNegocio")]
        public ErrorNegocio[] erroresNegocio {
            get {
                return this.erroresNegocioField;
            }
            set {
                this.erroresNegocioField = value;
                this.RaisePropertyChanged("erroresNegocio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class IdentificadorFuncionario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nroFuncionarioField;
        
        private Documento documentoField;
        
        private string usuarioRedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string nroFuncionario {
            get {
                return this.nroFuncionarioField;
            }
            set {
                this.nroFuncionarioField = value;
                this.RaisePropertyChanged("nroFuncionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Documento documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string usuarioRed {
            get {
                return this.usuarioRedField;
            }
            set {
                this.usuarioRedField = value;
                this.RaisePropertyChanged("usuarioRed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class Documento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codPaisEmisorField;
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string codPaisEmisor {
            get {
                return this.codPaisEmisorField;
            }
            set {
                this.codPaisEmisorField = value;
                this.RaisePropertyChanged("codPaisEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class Funcionario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nroFuncionarioField;
        
        private string nombre1Field;
        
        private string nombre2Field;
        
        private string apellido1Field;
        
        private string apellido2Field;
        
        private string usuarioRedField;
        
        private string codPaisEmisorField;
        
        private string paisEmisorField;
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        private string codSexoField;
        
        private string sexoField;
        
        private System.Nullable<System.DateTime> fechaNacimientoField;
        
        private System.Nullable<System.DateTime> fechaIngresoField;
        
        private string codRelacionFuncionalField;
        
        private string relacionFuncionalField;
        
        private string codUnidadField;
        
        private string unidadField;
        
        private string estadoField;
        
        private string codLugarFisicoField;
        
        private string lugarFisicoField;
        
        private string escalafonPresupuestalField;
        
        private string gradoPresupuestalField;
        
        private string cargoPresupuestalField;
        
        private string escalafonCobroField;
        
        private string gradoCobroField;
        
        private string cargoCobroField;
        
        private string eMailExternoField;
        
        private string numeroCCField;
        
        private string serieCCField;
        
        private string antiguedadField;
        
        private string causalEgresoField;
        
        private System.Nullable<System.DateTime> fechaEgresoField;
        
        private bool fechaEgresoFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaFinRelacionFuncionalField;
        
        private bool fechaFinRelacionFuncionalFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaVencimientoCarnetSaludField;
        
        private bool fechaVencimientoCarnetSaludFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string nroFuncionario {
            get {
                return this.nroFuncionarioField;
            }
            set {
                this.nroFuncionarioField = value;
                this.RaisePropertyChanged("nroFuncionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nombre1 {
            get {
                return this.nombre1Field;
            }
            set {
                this.nombre1Field = value;
                this.RaisePropertyChanged("nombre1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nombre2 {
            get {
                return this.nombre2Field;
            }
            set {
                this.nombre2Field = value;
                this.RaisePropertyChanged("nombre2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string apellido1 {
            get {
                return this.apellido1Field;
            }
            set {
                this.apellido1Field = value;
                this.RaisePropertyChanged("apellido1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string apellido2 {
            get {
                return this.apellido2Field;
            }
            set {
                this.apellido2Field = value;
                this.RaisePropertyChanged("apellido2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string usuarioRed {
            get {
                return this.usuarioRedField;
            }
            set {
                this.usuarioRedField = value;
                this.RaisePropertyChanged("usuarioRed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=6)]
        public string codPaisEmisor {
            get {
                return this.codPaisEmisorField;
            }
            set {
                this.codPaisEmisorField = value;
                this.RaisePropertyChanged("codPaisEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string paisEmisor {
            get {
                return this.paisEmisorField;
            }
            set {
                this.paisEmisorField = value;
                this.RaisePropertyChanged("paisEmisor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string nroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("nroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=10)]
        public string codSexo {
            get {
                return this.codSexoField;
            }
            set {
                this.codSexoField = value;
                this.RaisePropertyChanged("codSexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=14)]
        public string codRelacionFuncional {
            get {
                return this.codRelacionFuncionalField;
            }
            set {
                this.codRelacionFuncionalField = value;
                this.RaisePropertyChanged("codRelacionFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string relacionFuncional {
            get {
                return this.relacionFuncionalField;
            }
            set {
                this.relacionFuncionalField = value;
                this.RaisePropertyChanged("relacionFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=16)]
        public string codUnidad {
            get {
                return this.codUnidadField;
            }
            set {
                this.codUnidadField = value;
                this.RaisePropertyChanged("codUnidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
                this.RaisePropertyChanged("unidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string codLugarFisico {
            get {
                return this.codLugarFisicoField;
            }
            set {
                this.codLugarFisicoField = value;
                this.RaisePropertyChanged("codLugarFisico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string lugarFisico {
            get {
                return this.lugarFisicoField;
            }
            set {
                this.lugarFisicoField = value;
                this.RaisePropertyChanged("lugarFisico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string escalafonPresupuestal {
            get {
                return this.escalafonPresupuestalField;
            }
            set {
                this.escalafonPresupuestalField = value;
                this.RaisePropertyChanged("escalafonPresupuestal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string gradoPresupuestal {
            get {
                return this.gradoPresupuestalField;
            }
            set {
                this.gradoPresupuestalField = value;
                this.RaisePropertyChanged("gradoPresupuestal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string cargoPresupuestal {
            get {
                return this.cargoPresupuestalField;
            }
            set {
                this.cargoPresupuestalField = value;
                this.RaisePropertyChanged("cargoPresupuestal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string escalafonCobro {
            get {
                return this.escalafonCobroField;
            }
            set {
                this.escalafonCobroField = value;
                this.RaisePropertyChanged("escalafonCobro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string gradoCobro {
            get {
                return this.gradoCobroField;
            }
            set {
                this.gradoCobroField = value;
                this.RaisePropertyChanged("gradoCobro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string cargoCobro {
            get {
                return this.cargoCobroField;
            }
            set {
                this.cargoCobroField = value;
                this.RaisePropertyChanged("cargoCobro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string eMailExterno {
            get {
                return this.eMailExternoField;
            }
            set {
                this.eMailExternoField = value;
                this.RaisePropertyChanged("eMailExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string numeroCC {
            get {
                return this.numeroCCField;
            }
            set {
                this.numeroCCField = value;
                this.RaisePropertyChanged("numeroCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string serieCC {
            get {
                return this.serieCCField;
            }
            set {
                this.serieCCField = value;
                this.RaisePropertyChanged("serieCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=30)]
        public string antiguedad {
            get {
                return this.antiguedadField;
            }
            set {
                this.antiguedadField = value;
                this.RaisePropertyChanged("antiguedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string causalEgreso {
            get {
                return this.causalEgresoField;
            }
            set {
                this.causalEgresoField = value;
                this.RaisePropertyChanged("causalEgreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> fechaEgreso {
            get {
                return this.fechaEgresoField;
            }
            set {
                this.fechaEgresoField = value;
                this.RaisePropertyChanged("fechaEgreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEgresoSpecified {
            get {
                return this.fechaEgresoFieldSpecified;
            }
            set {
                this.fechaEgresoFieldSpecified = value;
                this.RaisePropertyChanged("fechaEgresoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=33)]
        public System.Nullable<System.DateTime> fechaFinRelacionFuncional {
            get {
                return this.fechaFinRelacionFuncionalField;
            }
            set {
                this.fechaFinRelacionFuncionalField = value;
                this.RaisePropertyChanged("fechaFinRelacionFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinRelacionFuncionalSpecified {
            get {
                return this.fechaFinRelacionFuncionalFieldSpecified;
            }
            set {
                this.fechaFinRelacionFuncionalFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinRelacionFuncionalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=34)]
        public System.Nullable<System.DateTime> fechaVencimientoCarnetSalud {
            get {
                return this.fechaVencimientoCarnetSaludField;
            }
            set {
                this.fechaVencimientoCarnetSaludField = value;
                this.RaisePropertyChanged("fechaVencimientoCarnetSalud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoCarnetSaludSpecified {
            get {
                return this.fechaVencimientoCarnetSaludFieldSpecified;
            }
            set {
                this.fechaVencimientoCarnetSaludFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoCarnetSaludSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ErrorNegocio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ResultObtenerFuncionarios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ItemFuncionario[] funcionariosField;
        
        private ErrorNegocio[] erroresNegocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itemFuncionario")]
        public ItemFuncionario[] funcionarios {
            get {
                return this.funcionariosField;
            }
            set {
                this.funcionariosField = value;
                this.RaisePropertyChanged("funcionarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errorNegocio")]
        public ErrorNegocio[] erroresNegocio {
            get {
                return this.erroresNegocioField;
            }
            set {
                this.erroresNegocioField = value;
                this.RaisePropertyChanged("erroresNegocio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ParamObtenerFuncionarios : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificadorFuncionario[] identificadoresFuncionariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identificadorFuncionario")]
        public IdentificadorFuncionario[] identificadoresFuncionarios {
            get {
                return this.identificadoresFuncionariosField;
            }
            set {
                this.identificadoresFuncionariosField = value;
                this.RaisePropertyChanged("identificadoresFuncionarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ResultObtenerEgresadosPeriodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Funcionario[] funcionariosEgresadosField;
        
        private ErrorNegocio[] erroresNegocioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("funcionario")]
        public Funcionario[] funcionariosEgresados {
            get {
                return this.funcionariosEgresadosField;
            }
            set {
                this.funcionariosEgresadosField = value;
                this.RaisePropertyChanged("funcionariosEgresados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errorNegocio")]
        public ErrorNegocio[] erroresNegocio {
            get {
                return this.erroresNegocioField;
            }
            set {
                this.erroresNegocioField = value;
                this.RaisePropertyChanged("erroresNegocio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ParamObtenerEgresadosPeriodo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> fechaDesdeField;
        
        private bool fechaDesdeFieldSpecified;
        
        private System.Nullable<System.DateTime> fechaHastaField;
        
        private bool fechaHastaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> fechaDesde {
            get {
                return this.fechaDesdeField;
            }
            set {
                this.fechaDesdeField = value;
                this.RaisePropertyChanged("fechaDesde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDesdeSpecified {
            get {
                return this.fechaDesdeFieldSpecified;
            }
            set {
                this.fechaDesdeFieldSpecified = value;
                this.RaisePropertyChanged("fechaDesdeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> fechaHasta {
            get {
                return this.fechaHastaField;
            }
            set {
                this.fechaHastaField = value;
                this.RaisePropertyChanged("fechaHasta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHastaSpecified {
            get {
                return this.fechaHastaFieldSpecified;
            }
            set {
                this.fechaHastaFieldSpecified = value;
                this.RaisePropertyChanged("fechaHastaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1")]
    public partial class ResultVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreServicioField;
        
        private string versionServicioField;
        
        private System.Nullable<System.DateTime> fechaExpiracionField;
        
        private bool fechaExpiracionFieldSpecified;
        
        private string versionEstandarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nombreServicio {
            get {
                return this.nombreServicioField;
            }
            set {
                this.nombreServicioField = value;
                this.RaisePropertyChanged("nombreServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string versionServicio {
            get {
                return this.versionServicioField;
            }
            set {
                this.versionServicioField = value;
                this.RaisePropertyChanged("versionServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> fechaExpiracion {
            get {
                return this.fechaExpiracionField;
            }
            set {
                this.fechaExpiracionField = value;
                this.RaisePropertyChanged("fechaExpiracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaExpiracionSpecified {
            get {
                return this.fechaExpiracionFieldSpecified;
            }
            set {
                this.fechaExpiracionFieldSpecified = value;
                this.RaisePropertyChanged("fechaExpiracionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string versionEstandar {
            get {
                return this.versionEstandarField;
            }
            set {
                this.versionEstandarField = value;
                this.RaisePropertyChanged("versionEstandar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.version version;
        
        public versionRequest() {
        }
        
        public versionRequest(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.version version) {
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultVersion ResultVersion;
        
        public versionResponse() {
        }
        
        public versionResponse(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultVersion ResultVersion) {
            this.ResultVersion = ResultVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerEgresadosPeriodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerEgresadosPeriodo obtenerEgresadosPeriodo;
        
        public obtenerEgresadosPeriodoRequest() {
        }
        
        public obtenerEgresadosPeriodoRequest(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerEgresadosPeriodo obtenerEgresadosPeriodo) {
            this.obtenerEgresadosPeriodo = obtenerEgresadosPeriodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerEgresadosPeriodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerEgresadosPeriodo ResultObtenerEgresadosPeriodo;
        
        public obtenerEgresadosPeriodoResponse() {
        }
        
        public obtenerEgresadosPeriodoResponse(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerEgresadosPeriodo ResultObtenerEgresadosPeriodo) {
            this.ResultObtenerEgresadosPeriodo = ResultObtenerEgresadosPeriodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFuncionariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerFuncionarios obtenerFuncionarios;
        
        public obtenerFuncionariosRequest() {
        }
        
        public obtenerFuncionariosRequest(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerFuncionarios obtenerFuncionarios) {
            this.obtenerFuncionarios = obtenerFuncionarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFuncionariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bps.gub.uy/Personal/wssFuncionarios/v1", Order=0)]
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerFuncionarios ResultObtenerFuncionarios;
        
        public obtenerFuncionariosResponse() {
        }
        
        public obtenerFuncionariosResponse(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerFuncionarios ResultObtenerFuncionarios) {
            this.ResultObtenerFuncionarios = ResultObtenerFuncionarios;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVirtualInterfaceChannel : Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirtualInterfaceClient : System.ServiceModel.ClientBase<Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface>, Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface {
        
        public VirtualInterfaceClient() {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionResponse Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface.version(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionRequest request) {
            return base.Channel.version(request);
        }
        
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultVersion version(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.version version1) {
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionRequest inValue = new Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionRequest();
            inValue.version = version1;
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.versionResponse retVal = ((Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface)(this)).version(inValue);
            return retVal.ResultVersion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoResponse Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface.obtenerEgresadosPeriodo(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoRequest request) {
            return base.Channel.obtenerEgresadosPeriodo(request);
        }
        
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerEgresadosPeriodo obtenerEgresadosPeriodo(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerEgresadosPeriodo obtenerEgresadosPeriodo1) {
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoRequest inValue = new Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoRequest();
            inValue.obtenerEgresadosPeriodo = obtenerEgresadosPeriodo1;
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerEgresadosPeriodoResponse retVal = ((Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface)(this)).obtenerEgresadosPeriodo(inValue);
            return retVal.ResultObtenerEgresadosPeriodo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosResponse Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface.obtenerFuncionarios(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosRequest request) {
            return base.Channel.obtenerFuncionarios(request);
        }
        
        public Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ResultObtenerFuncionarios obtenerFuncionarios(Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.ParamObtenerFuncionarios obtenerFuncionarios1) {
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosRequest inValue = new Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosRequest();
            inValue.obtenerFuncionarios = obtenerFuncionarios1;
            Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.obtenerFuncionariosResponse retVal = ((Bull.PRES.Poderes.ServiceAgents.Servicios.wssFuncionarios.IVirtualInterface)(this)).obtenerFuncionarios(inValue);
            return retVal.ResultObtenerFuncionarios;
        }
    }
}
